version: '3.7'
services:
  app:
    container_name: schullz-app-dev
    environment:
    - COMPOSER_MEMORY_LIMIT=-1
    image: ejklock/php-fpm-pgdb:7.4
    networks:
    - schullzNetwork
    restart: unless-stopped
    volumes:
    - ./:/var/www/app
    - ./docker-compose/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/app
  # db:
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: schullz-dev-db
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_NAME: mysql
  #     SERVICE_TAGS: dev
  #   image: mysql:5.7
  #   networks:
  #   - schullzNetwork
  #   ports:
  #   - ${DB_EXTERNAL_PORT}:${DB_PORT}
  #   restart: unless-stopped
  #   tty: true
  #   volumes:
  #   - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  #   - schullzMysqlData:/var/lib/mysql
  nginx:
    container_name: schullz-dev-nginx
    image: nginx:alpine
    networks:
    - schullzNetwork
    ports:
    - 8000:80
    restart: unless-stopped
    volumes:
    - ./:/var/www/app
    - ./docker-compose/nginx:/etc/nginx/conf.d/
    working_dir: /var/www/app
networks:
  schullzNetwork:
    driver: bridge
volumes:
  schullzMysqlData:
    driver: local
    name: schullzMysqlData
